parameters:
#    aula_backend.example.class: Aula\BackendBundle\Example

services:
#    aula_backend.example:
#        class: %aula_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
