aula_user:
    resource: "@AulaUserBundle/Resources/config/routing.yml"
    prefix:   /

aula_backend:
    resource: "@AulaBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

aula_frontend:
    resource: "@AulaFrontendBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /perfil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /cadastro

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /perfil

