

fos_user_resetting_request:
    path:  /
    defaults: { _controller: FOSUserBundle:Resetting:request }
    requirements: { _method: GET }

fos_user_resetting_send_email:
    pattern: /enviar-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    requirements: { _method: POST }

fos_user_resetting_check_email:
    pattern: /check
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements: { _method: GET }

fos_user_resetting_reset:
    pattern: /resetar/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    requirements: { _method: GET|POST}
