aula_frontend_homepage:
    path:     /
    defaults: { _controller: AulaFrontendBundle:Default:index }

aula_frontend_register:
    path:     /cadastrar
    defaults: { _controller: AulaFrontendBundle:Default:register }

aula_frontend_grade_create:
    path:     /salvar
    defaults: { _controller: AulaFrontendBundle:Default:myGradeCreate }

aula_frontend_classes:
    path:     /aulas
    defaults: { _controller: AulaFrontendBundle:Default:classes }


aula_frontend_view_teacher:
    path:     /professor/{id}
    defaults: { _controller: AulaFrontendBundle:Default:viewTeacher }

#aula_frontend_schedule:
#    path:     /agendar/{teacher}
#    defaults: { _controller: AulaFrontendBundle:Default:schedule }

AulaBackendBundle_schedule:
        resource: "@AulaBackendBundle/Resources/config/routing/schedule.yml"
        prefix:   /agendar

aula_frontend_accept:
    path:     /aceitar/{id}/{accept}
    defaults: { _controller: AulaFrontendBundle:Default:acceptRequest }

AulaBackendBundle_rating:
        resource: "@AulaBackendBundle/Resources/config/routing/rating.yml"
        prefix:   /avaliar

aula_start:
    path:     /iniciar-aula/{class}
    defaults: { _controller: AulaFrontendBundle:Default:startClass }