parameters:
#    aula_frontend.example.class: Aula\FrontendBundle\Example

services:
#    aula_frontend.example:
#        class: %aula_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    aula_user.registration.form.type:
        class: Aula\BackendBundle\Form\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name:  form.type, alias: aula_user_registration }
